apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nebula-budget
  labels:
    app: nebula-budget
spec:
  selector:
    matchLabels:
      app: nebula-storaged
      app: nebula-metad
  maxUnavailable: 1