/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "./gen-cpp2/hbase_data.h"

namespace apache { namespace hadoop { namespace hbase { namespace thrift2 { namespace cpp2 {

constexpr const std::size_t _TDeleteTypeEnumDataStorage::size;
constexpr const std::array<TDeleteType, 2> _TDeleteTypeEnumDataStorage::values;
constexpr const std::array<folly::StringPiece, 2> _TDeleteTypeEnumDataStorage::names;

}}}}} // apache::hadoop::hbase::thrift2::cpp2
namespace apache { namespace thrift {

}} // apache::thrift
namespace apache { namespace hadoop { namespace hbase { namespace thrift2 { namespace cpp2 {

constexpr const std::size_t _TDurabilityEnumDataStorage::size;
constexpr const std::array<TDurability, 4> _TDurabilityEnumDataStorage::values;
constexpr const std::array<folly::StringPiece, 4> _TDurabilityEnumDataStorage::names;

}}}}} // apache::hadoop::hbase::thrift2::cpp2
namespace apache { namespace thrift {

}} // apache::thrift
namespace apache { namespace hadoop { namespace hbase { namespace thrift2 { namespace cpp2 {

constexpr const std::size_t _TCompareOpEnumDataStorage::size;
constexpr const std::array<TCompareOp, 7> _TCompareOpEnumDataStorage::values;
constexpr const std::array<folly::StringPiece, 7> _TCompareOpEnumDataStorage::names;

}}}}} // apache::hadoop::hbase::thrift2::cpp2
namespace apache { namespace thrift {

}} // apache::thrift

