/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "./gen-cpp2/hbase_constants.h"

#include <folly/Indestructible.h>

namespace apache { namespace hadoop { namespace hbase { namespace thrift2 { namespace cpp2 {

}}}}} // apache::hadoop::hbase::thrift2::cpp2
