/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include <thrift/lib/cpp2/protocol/Protocol.h>

#include "./gen-cpp2/hbase_types.h"

namespace apache { namespace hadoop { namespace hbase { namespace thrift2 { namespace cpp2 {

struct hbase_constants {

};

}}}}} // apache::hadoop::hbase::thrift2::cpp2
