/* Copyright (c) 2020 vesoft inc. All rights reserved.
 *
 * This source code is licensed under Apache 2.0 License,
 * attached with Common Clause Condition 1.0, found in the LICENSES directory.
 */

#ifndef STORAGE_INDEXPOLICYMAKER_H
#define STORAGE_INDEXPOLICYMAKER_H
#include "base/Base.h"
#include "meta/SchemaManager.h"
<<<<<<< HEAD
#include "meta/IndexManager.h"
#include "storage/CommonUtils.h"
#include "storage/BaseProcessor.h"
=======
#include "storage/CommonUtils.h"
#include "storage/index/IndexOptimizer.h"
>>>>>>> 1, Addressed comments. 2, Optimized index scan logic.

namespace nebula {
namespace storage {

<<<<<<< HEAD
/**
 * OperatorList used record all scan filters, before create scan policy,
 * need collect all columns and values for prefix string.
 * std::tuple<Column name, Value, Operator>;
 */
using OperatorItem = std::tuple<std::string, VariantType, RelationalExpression::Operator>;

class IndexPolicyMaker {
=======
enum class PolicyType : uint8_t {
    SIMPLE_POLICY      = 0x01,
    OPTIMIZED_POLICY   = 0x02,
};

enum class PolicyScanType : uint8_t {
    SEEK_SCAN          = 0x01,
    PREFIX_SCAN        = 0x02,
    ACCURATE_SCAN      = 0x03,
};

using OperatorList = std::vector<std::pair<std::pair<std::string, VariantType>, bool>>;

class IndexPolicyMaker : IndexOptimizer{
>>>>>>> 1, Addressed comments. 2, Optimized index scan logic.
public:
    virtual ~IndexPolicyMaker() = default;

protected:
<<<<<<< HEAD
    explicit IndexPolicyMaker(meta::SchemaManager *schemaMan,
                              meta::IndexManager* indexMan)
        : schemaMan_(schemaMan)
        , indexMan_(indexMan) {}

    /**
     * Details Entry method of index scan policy preparation, process logic as below :
     *         1, Trigger optimizer to optimize expression nodes
     *         2, Traverse the optimized expression, analyze and confirm PolicyType,
     *            confirm scanning mode.
     * Param  filter : From encoded string of where clause.
     * Return ErrorCode
     **/
    cpp2::ErrorCode preparePolicy(const std::string &filter);

    /**
     * Details Index scan policy generator. Confirm how to generate the scan policy
     *         through the information generated by policyPrepare. Generate corresponding
     *         execution policy according to PolicyType.
     *         In this method, it is best to use as many index columns as possible.
     **/
    void buildPolicy();

    /**
     * Details Evaluate filter conditions.
     */
    bool exprEval(Getters &getters);

private:
    cpp2::ErrorCode decodeExpression(const std::string &filter);

    /**
     * Details Entry method of expresion traverse.
     */

    cpp2::ErrorCode traversalExpression(const Expression *expr);

protected:
    meta::SchemaManager*                     schemaMan_{nullptr};
    meta::IndexManager*                      indexMan_{nullptr};
    std::unique_ptr<ExpressionContext>       expCtx_{nullptr};
    std::unique_ptr<Expression>              exp_{nullptr};
    std::string                              prefix_;
    std::shared_ptr<nebula::cpp2::IndexItem> index_{nullptr};
    bool                                     optimizedPolicy_{true};
    bool                                     requiredFilter_{true};
    std::vector<OperatorItem>                operatorList_;
=======
    explicit IndexPolicyMaker(meta::SchemaManager *schemaMan)
        : IndexOptimizer()
        , schemaMan_(schemaMan) {}

    cpp2::ErrorCode policyPrepare(const std::string& filter);

    cpp2::ErrorCode policyGenerate();

private:
    cpp2::ErrorCode initPolicy();

    std::string prepareAPE(const Expression* expr);

    StatusOr<VariantType> preparePE(const Expression* expr);

    cpp2::ErrorCode prepareRFE(const Expression* expr);

    cpp2::ErrorCode prepareLE(const LogicalExpression* expr);

    cpp2::ErrorCode prepareExpression(const Expression* expr);

protected:
    std::unique_ptr<Expression> expr_{nullptr};
    meta::SchemaManager*        schemaMan_{nullptr};
    nebula::cpp2::IndexItem     index_;
    std::vector<VariantType>    policies_;
    PolicyType                  policyType_{PolicyType::OPTIMIZED_POLICY};
    PolicyScanType              policyScanType_{PolicyScanType::SEEK_SCAN};
    OperatorList                operatorList_;
>>>>>>> 1, Addressed comments. 2, Optimized index scan logic.
};
}  // namespace storage
}  // namespace nebula
#endif  // STORAGE_INDEXPOLICYMAKER_H
