/* Copyright (c) 2018 - present, VE Software Inc. All rights reserved
 *
 * This source code is licensed under Apache 2.0 License
 *  (found in the LICENSE.Apache file in the root directory)
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vesoft_client_NativeClient */

#ifndef _Included_com_vesoft_client_NativeClient
#define _Included_com_vesoft_client_NativeClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vesoft_client_NativeClient
 * Method:    encode
 * Signature: ([Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vesoft_client_NativeClient_encode
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_vesoft_client_NativeClient_OptionsBuilder */

#ifndef _Included_com_vesoft_client_NativeClient_OptionsBuilder
#define _Included_com_vesoft_client_NativeClient_OptionsBuilder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
