version: '3.4'
services:
  metad:
    image: vesoft/nebula-metad:nightly
    environment:
      USER: root
    command: ["--meta_server_addrs=172.28.1.1:45500", "--local_ip=172.28.1.1", "--port=45500"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      nebula-net:
        ipv4_address: 172.28.1.1

  storaged:
    image: vesoft/nebula-storaged:nightly
    environment:
      USER: root
    command: ["--meta_server_addrs=172.28.1.1:45500", "--local_ip=172.28.1.2", "--port=44500"]
    depends_on:
      - metad
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      nebula-net:
        ipv4_address: 172.28.1.2

  graphd:
    image: vesoft/nebula-graphd:nightly
    environment:
      USER: root
    command: ["--meta_server_addrs=172.28.1.1:45500", "--port=3699"]
    depends_on:
      - metad
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      nebula-net:
        ipv4_address: 172.28.1.3

  console:
    image: vesoft/nebula-console:nightly
    environment:
      USER: root
    entrypoint:
      - ./bin/nebula
      - -u
      - user
      - -p
      - password
      - --addr=172.28.1.3
      - --port=3699
    depends_on:
      - graphd
    networks:
      nebula-net:
        ipv4_address: 172.28.1.4

networks:
  nebula-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
