FROM vesoft/nebula-dev:centos7 as builder

COPY . /home/nebula/BUILD

RUN cd /home/nebula/BUILD/package \
  && ./package.sh -v $(git rev-parse --short HEAD) -n OFF

FROM centos:7

COPY --from=builder /home/nebula/BUILD/build/nebula-*-Linux-console.rpm /usr/local/nebula/nebula-console.rpm

WORKDIR /usr/local/nebula

RUN rpm -ivh *.rpm \
  && mkdir -p ./{logs,data,pids} \
  && rm -rf *.rpm

ENTRYPOINT ["./bin/nebula", "-u", "user", "-p", "password"]
