FROM vesoft/nebula-dev:centos7 as builder

ARG BRANCH=master
ARG VERSION=

COPY . /home/nebula/BUILD

RUN cd /home/nebula/BUILD/package \
  && ./package.sh -n OFF -v "${VERSION}" -b ${BRANCH} -t RelWithDebInfo -s TRUE -c OFF -k ON 

FROM centos:7

COPY --from=builder /home/nebula/BUILD/pkg-build/cpack_output/nebula-*-tool.rpm /usr/local/nebula/nebula-tool.rpm

WORKDIR /usr/local/nebula

RUN rpm -ivh *.rpm \
  && rm -rf *.rpm

# default entrypoint
ENTRYPOINT ["/usr/local/nebula/bin/db_dump"]
