FROM vesoft/nebula-dev:centos7 as builder

COPY . /home/nebula/BUILD

RUN cd /home/nebula/BUILD/package \
  && ./package.sh -v $(git rev-parse --short HEAD)

FROM centos:7

COPY --from=builder /home/nebula/BUILD/build/cpack_output/*.rpm /usr/local/nebula/

WORKDIR /usr/local/nebula

RUN rpm -ivh *.rpm \
  && mkdir -p ./{logs,data,pids} \
  && rm -rf *.rpm

# meta ports
EXPOSE 45500 45501 11000 11002
# storage ports
EXPOSE 44500 44501 12000 12002
# graph ports
EXPOSE 3699 13000 13002
