version: '3.4'
services:
  metad0:
    image: vesoft/nebula-metad:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.28.1.1:45500,172.28.1.2:45500,172.28.1.3:45500
      - --local_ip=172.28.1.1
      - --ws_ip=172.28.1.1
      - --port=45500
      - --load_data_interval_secs=5
      - --data_path=/data/meta
      - --log_dir=/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 11000
      - 11002
    volumes:
      - ./data/meta0:/data/meta
      - ./logs/meta0:/logs
    networks:
      nebula-net:
        ipv4_address: 172.28.1.1
    restart: on-failure

  metad1:
    image: vesoft/nebula-metad:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.28.1.1:45500,172.28.1.2:45500,172.28.1.3:45500
      - --local_ip=172.28.1.2
      - --ws_ip=172.28.1.2
      - --port=45500
      - --load_data_interval_secs=5
      - --data_path=/data/meta
      - --log_dir=/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 11000
      - 11002
    volumes:
      - ./data/meta1:/data/meta
      - ./logs/meta1:/logs
    networks:
      nebula-net:
        ipv4_address: 172.28.1.2
    restart: on-failure

  metad2:
    image: vesoft/nebula-metad:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.28.1.1:45500,172.28.1.2:45500,172.28.1.3:45500
      - --local_ip=172.28.1.3
      - --ws_ip=172.28.1.3
      - --port=45500
      - --load_data_interval_secs=5
      - --data_path=/data/meta
      - --log_dir=/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 11000
      - 11002
    volumes:
      - ./data/meta2:/data/meta
      - ./logs/meta2:/logs
    networks:
      nebula-net:
        ipv4_address: 172.28.1.3
    restart: on-failure

  storaged0:
    image: vesoft/nebula-storaged:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.28.1.1:45500,172.28.1.2:45500,172.28.1.3:45500
      - --local_ip=172.28.2.1
      - --ws_ip=172.28.2.1
      - --port=44500
      - --data_path=/data/storage
      - --log_dir=/logs
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 12000
      - 12002
    volumes:
      - ./data/storage0:/data/storage
      - ./logs/storage0:/logs
    networks:
      nebula-net:
        ipv4_address: 172.28.2.1
    restart: on-failure

  storaged1:
    image: vesoft/nebula-storaged:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.28.1.1:45500,172.28.1.2:45500,172.28.1.3:45500
      - --local_ip=172.28.2.2
      - --ws_ip=172.28.2.2
      - --port=44500
      - --data_path=/data/storage
      - --log_dir=/logs
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 12000
      - 12002
    volumes:
      - ./data/storage1:/data/storage
      - ./logs/storage1:/logs
    networks:
      nebula-net:
        ipv4_address: 172.28.2.2
    restart: on-failure

  storaged2:
    image: vesoft/nebula-storaged:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.28.1.1:45500,172.28.1.2:45500,172.28.1.3:45500
      - --local_ip=172.28.2.3
      - --ws_ip=172.28.2.3
      - --port=44500
      - --data_path=/data/storage
      - --log_dir=/logs
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 12000
      - 12002
    volumes:
      - ./data/storage2:/data/storage
      - ./logs/storage2:/logs
    networks:
      nebula-net:
        ipv4_address: 172.28.2.3
    restart: on-failure

  graphd0:
    image: vesoft/nebula-graphd:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.28.1.1:45500,172.28.1.2:45500,172.28.1.3:45500
      - --port=3699
      - --ws_ip=172.28.3.1
      - --load_data_interval_secs=5
      - --log_dir=/logs
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 3699
      - 13000
      - 13002
    volumes:
      - ./logs/graph0:/logs
    networks:
      nebula-net:
        ipv4_address: 172.28.3.1
    restart: on-failure

  graphd1:
    image: vesoft/nebula-graphd:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.28.1.1:45500,172.28.1.2:45500,172.28.1.3:45500
      - --port=3699
      - --ws_ip=172.28.3.2
      - --load_data_interval_secs=5
      - --log_dir=/logs
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 3699
      - 13000
      - 13002
    volumes:
      - ./logs/graph1:/logs
    networks:
      nebula-net:
        ipv4_address: 172.28.3.2
    restart: on-failure

  graphd2:
    image: vesoft/nebula-graphd:nightly
    environment:
      USER: root
    command:
      - --meta_server_addrs=172.28.1.1:45500,172.28.1.2:45500,172.28.1.3:45500
      - --port=3699
      - --ws_ip=172.28.3.3
      - --load_data_interval_secs=5
      - --log_dir=/logs
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13000/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 3699
      - 13000
      - 13002
    volumes:
      - ./logs/graph2:/logs
    networks:
      nebula-net:
        ipv4_address: 172.28.3.3
    restart: on-failure

networks:
  nebula-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
