list(APPEND NEBULA_CLANG_FLAGS
    "-Wall"
    "-Wextra"
    "-Weverything"
    "-Wno-c++98-compat-pedantic"
    "-Wno-conversion"
    "-Wno-covered-switch-default"
    "-Wno-deprecated"
    "-Wno-disabled-macro-expansion"
    "-Wno-double-promotion"
    "-Wno-comma"
    "-Wno-extra-semi"
    "-Wno-extra-semi-stmt"
    "-Wno-packed"
    "-Wno-padded"
    "-Wno-sign-compare"
    "-Wno-float-conversion"
    "-Wno-float-equal"
    "-Wno-format-nonliteral"
    "-Wno-gcc-compat"
    "-Wno-global-constructors"
    "-Wno-exit-time-destructors"
    "-Wno-nested-anon-types"
    "-Wno-non-modular-include-in-module"
    "-Wno-old-style-cast"
    "-Wno-range-loop-analysis"
    "-Wno-reserved-id-macro"
    "-Wno-shorten-64-to-32"
    "-Wno-switch-enum"
    "-Wno-thread-safety-negative"
    "-Wno-unknown-warning-option"
    "-Wno-unreachable-code"
    "-Wno-unused-macros"
    "-Wno-weak-vtables"
    "-Wno-zero-as-null-pointer-constant"
    "-Wbitfield-enum-conversion"
    "-Wbool-conversion"
    "-Wconstant-conversion"
    "-Wenum-conversion"
    "-Wint-conversion"
    "-Wliteral-conversion"
    "-Wnon-literal-null-conversion"
    "-Wnull-conversion"
    "-Wobjc-literal-conversion"
    "-Wno-sign-conversion"
    "-Wstring-conversion"
#We will enable these warnings in the future.
    "-Wno-documentation-unknown-command"
    "-Wno-c++17-extensions"
    "-Wno-date-time"
    "-Wno-return-std-move-in-c++11"
    "-Wno-missing-prototypes"
    "-Wno-missing-variable-declarations"
    "-Wno-inconsistent-missing-destructor-override"
    "-Wno-implicit-fallthrough"
    "-Wno-gnu-zero-variadic-macro-arguments"
    "-Wno-shadow-field"
    "-Wno-cast-align"
    "-Wno-overloaded-virtual"
    "-Wno-self-move"
    "-Wno-self-assign-overloaded"
    "-Wno-undefined-reinterpret-cast"
)

list(APPEND NEBULA_GCC_FLAGS
    "-Wall"
#Since there are no more versions of gcc for testing at this time, only -Wall is turned on by default, 
#and the rest We will enable it in the future.
    # "-Wextra"
    # "-Wcast-qual"
    # "-Wconversion-null"
    # "-Wmissing-declarations"
    # "-Woverlength-strings"
    # "-Wpointer-arith"
    # "-Wunused-local-typedefs"
    # "-Wunused-result"
    # "-Wvarargs"
    # "-Wvla"
    # "-Wwrite-strings"
    # "-Wno-missing-field-initializers"
    # "-Wno-sign-compare"
)
