#!/bin/bash

daemons=(metad graphd storaged)
for daemon in ${daemons[@]}
do
    if [[ ! -f $RPM_INSTALL_PREFIX/etc/nebula-${daemon}.conf ]] && [[ -f $RPM_INSTALL_PREFIX/etc/nebula-${daemon}.conf.default ]]; then
        cp $RPM_INSTALL_PREFIX/etc/nebula-${daemon}.conf.default $RPM_INSTALL_PREFIX/etc/nebula-${daemon}.conf
        chmod 644 $RPM_INSTALL_PREFIX/etc/nebula-${daemon}.conf
    fi
    if [[ -f $RPM_INSTALL_PREFIX/etc/unit/nebula-${daemon}.service ]]; then
        if [[ ! -d /usr/lib/systemd/system ]]; then
           echo "WARNING! Failed to install systemd script successfully."
        else
           cp $RPM_INSTALL_PREFIX/etc/unit/nebula-${daemon}.service /usr/lib/systemd/system
           num=`grep -n "ExecStart" /usr/lib/systemd/system/nebula-${daemon}.service | awk -F: '{print $1}'`
           sed -i "${num}d" /usr/lib/systemd/system/nebula-${daemon}.service
           sed -i "${num} i ExecStart=$RPM_INSTALL_PREFIX/scripts/nebula.service start ${daemon}" \
               /usr/lib/systemd/system/nebula-${daemon}.service
        fi
    fi
done

if [[ -f $RPM_INSTALL_PREFIX/etc/unit/nebula.service ]]; then
    if [[ ! -d /usr/lib/systemd/system ]]; then
        echo "WARNING! Failed to install systemd script successfully."
    else
        cp $RPM_INSTALL_PREFIX/etc/unit/nebula.service /usr/lib/systemd/system
        num=`grep -n "ExecStart" /usr/lib/systemd/system/nebula.service | awk -F: '{print $1}'`
        sed -i "${num}d" /usr/lib/systemd/system/nebula.service
        sed -i "${num} i ExecStart=$RPM_INSTALL_PREFIX/scripts/nebula.service start all" \
            /usr/lib/systemd/system/nebula.service
fi

