name: Auto Cherry Pick 
on:
  workflow_dispatch:
    inputs:
      pr_label:
        description: "Cherry pick label such as 'cherry-pick-v3.2'"
        required: true

defaults:
  run:
    shell: bash

jobs:
  auto-cherry-pick:
      #if: ${{ startsWith(github.event.pull_request.labels.*.name, 'cherry-pick-') && github.event.pull_request.merged == true }}
      runs-on: ubuntu-latest
      container:
        image: nebula-dev:centos7
      steps:
        - name: keep workspace empty  
          run: |
            rm -rf *
        - name: auto cherry pick
          uses: xigongdaEricyang/cherry-pick-robot@with-python
          with:
              repo_token: ${{ secrets.GH_BOT_PAT }}
              pr_label: ${{ github.event.inputs.prlabel }}
              #pr_num: ${{ github.event.pull_request.number }}
              auto_merge: true
