name: Nebula Build and Test Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        tag: [centos6, centos7, ubuntu1604, ubuntu1804]
    container:
      image: vesoft/nebula-dev:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: cmake
        run: |
          mkdir _build
          cd _build && cmake ..
        shell: bash
      - name: make
        run: cd _build && make -j $(nproc)
        shell: bash
      - name: test
        run: cd _build && ctest -j $(nproc) --output-on-failure
        shell: bash
