name: Nebula Build and Test Workflow

on:
  push:
    paths:
      - '*'
      - '!/docs/*'

jobs:
  # lint:
  #   name: cpp-lint
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: make
        uses: actions/checkout@v1
        uses: docker://vesoft/nebula-dev:centos
          with:
            fetch-depth: 1
        run: docker run --rm -it -v $(pwd):/home/nebula vesoft/nebula-dev:centos /bin/bash -c ". /etc/profile.d/devtoolset-8-enable.sh && mkdir _build && cd _build && cmake .. && make -j"
        id: build
      - name: ctest
        uses: actions/checkout@v1
        uses: docker://vesoft/nebula-dev:centos
        run: docker run --rm -v $(pwd):/home/nebula vesoft/nebula-dev:centos /bin/bash -c 'cd _build && ctest'
