name: Nebula Build and Test Workflow

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    container:
      image: vesoft/nebula-dev:centos
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: cmake
        run: |
          . /etc/profile.d/devtoolset-8-enable.sh
          mkdir _build
          cd _build && cmake ..
        shell: bash
      - name: make
        run: |
          . /etc/profile.d/devtoolset-8-enable.sh
          cd _build && make -j2
        shell: bash
      - name: test
        run: |
          . /etc/profile.d/devtoolset-8-enable.sh
          cd _build && ctest --output-on-failure
        shell: bash
