name: Nebula Build and Test Workflow

on:
- push
- pull_request:
    paths:
      - '*'
      - '!/docs/*'

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    container:
      image: vesoft/nebula-dev:centos
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: make
        run: |
          . /etc/profile.d/devtoolset-8-enable.sh
          mkdir _build
          cd _build
          cmake ..
          make -j
      - name: test
        run: cd _build && ctest
