name: docker

on:
  schedule:
    - cron: '0 18 * * *'

jobs:
  docker:
    name: build docker image
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        service:
          - metad
          - storaged
          - graphd
          - console
          - graph
    steps:
      - uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/nebula-${{ matrix.service }}:nightly
        run: |
          docker build -t ${IMAGE_NAME} -f docker/Dockerfile.${{ matrix.service }} .
          docker push ${IMAGE_NAME}
        shell: bash
