name: docker

on:
  schedule:
    - cron: '0 18 * * *'
  push:
    branches:
      - 'v[0-9]+.*'
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  docker:
    name: build docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - metad
          - storaged
          - graphd
          - console
          - graph
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Compute tag
        id: tag
        run: |
          [[ "${{ github.event_name }}" == "push" ]] && \
            echo "::set-output name=tag::$(cut -d/ -f3 <<< ${{ github.ref }})" || \
            echo "::set-output name=tag::nightly"
        shell: bash
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/nebula-${{ matrix.service }}
          tags: ${{ steps.tag.outputs.tag }}
          dockerfile: docker/Dockerfile.${{ matrix.service }}
          cache_froms: vesoft/nebula-dev:centos7
          add_git_labels: true
