name: docker

on:
  schedule:
    - cron: '0 18 * * *'
  release:
    types:
      - published

jobs:
  docker:
    name: build docker image
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        service:
          - metad
          - storaged
          - graphd
          - console
          - graph
    steps:
      - uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build nightly image
        if: github.event_name == 'schedule'
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/nebula-${{ matrix.service }}:nightly
        run: |
          docker build -t ${IMAGE_NAME} -f docker/Dockerfile.${{ matrix.service }} .
          docker push ${IMAGE_NAME}
        shell: bash
      - name: build release image
        if: github.event_name == 'release'
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/nebula-${{ matrix.service }}
        run: |
          TAG=$(git describe --exact-match --abbrev=0 --tags)
          docker build -t ${IMAGE_NAME}:${TAG} -f docker/Dockerfile.${{ matrix.service }} .
          docker push ${IMAGE_NAME}:${TAG}
        shell: bash
